### ISSUE TITLE
react app nut running due to missing ./navbar.css file

### ISSUE THREAD

**Issue by sambit826059** [sambit826059/Placement_Module#4]
the error shows missing of ./navbar.css in the project directory. 
The whole error message is :

{
          Failed to compile.
          
          Module not found: Error: Can't resolve './Navbar.css' in '/home/sambit/Desktop/devFolder/Final year project/placement_module/src/Components'
          ERROR in ./src/Components/NavBar.jsx 6:0-22
          Module not found: Error: Can't resolve './Navbar.css' in '/home/sambit/Desktop/devFolder/Final year project/placement_module/src/Components'
          
          webpack compiled with 1 error
          One of your dependencies, babel-preset-react-app, is importing the
          "@babel/plugin-proposal-private-property-in-object" package without
          declaring it in its dependencies. This is currently working because
          "@babel/plugin-proposal-private-property-in-object" is already in your
          node_modules folder for unrelated reasons, but it may break at any time.
          
          babel-preset-react-app is part of the create-react-app project, which
          is not maintianed anymore. It is thus unlikely that this bug will
          ever be fixed. Add "@babel/plugin-proposal-private-property-in-object" to
          your devDependencies to work around this error. This will make this message
          go away.
}

**Comment by soumen974** [comment]
this is updated ,
